UI-20:Component avatar
promising-inctagram/inctagram pull request #20
Opened 2024-09-16 09:40 UTC by tolkunio

2024-09-16 15:59 UTC, atpradical requested changes

2024-09-16 15:59 UTC, atpradical commented on src/components/avatar/Avatar.tsx
> +} & ComponentPropsWithoutRef<typeof AvatarPrimitive.Root>
было бы классно иметь возможность передавать размер аватарки в виде s | m | l  и тд размеров. 
что то на подобии варианта как в других компонентах.

Для этого надо посмотреть варианты использования аватара в макете и предусмотреть эти рзамеры как тип в пропсах.

2024-09-16 15:59 UTC, atpradical commented on src/components/avatar/Avatar.tsx
> +export const Avatar = ({ className, size = 204, src, userName, ...rest }: AvatarProps) => {
после того как добавишь варианты размеров, здесь можно заменить размер по умолчанию например на M (ну будет зависеть от того какой размер чаще всего встречается в макете)

2024-09-16 15:59 UTC, atpradical commented on src/components/avatar/Avatar.tsx
> +        style={{ height: `${size}px`, width: `${size}px` }}
плохая идея использовать inline стили в компоненте.

2024-09-19 06:04 UTC, blindstttealer approved these changes

2024-09-19 08:47 UTC, Kristina-Tur approved these changes

2024-09-19 11:34 UTC, atpradical requested changes
Ошибки при компиляции TS:
TS2362: The left-hand side of an arithmetic operation must be of type any, number, bigint or an enum type.

2024-09-20 16:36 UTC, atpradical approved these changes

2024-09-20 16:36 UTC, merged