Review Request: Alert component - feedback needed
promising-inctagram/inctagram pull request #27
Opened 2024-09-20 13:17 UTC by blindstttealer

2024-09-20 16:27 UTC, atpradical requested changes
Storybook не компилится. 

![image](https://github.com/user-attachments/assets/0d647129-07a2-472c-ae6f-f523656885f2)

2024-09-22 16:47 UTC, atpradical approved these changes

2024-09-22 16:47 UTC, atpradical commented on src/components/toast/Toast.stories.tsx
я бы предложил сделать одну стори, в ней кнопки на каждый вариант тостера. Кликаешь на них и смотришь на тостер.
И еще я бы предложил не центровать по центру экрана, потому что это иногда не удобно.

2024-09-22 16:47 UTC, atpradical commented on src/components/toast/Toast.tsx
> +const DEFAULT_POSITION = 'bottom-left'
я бы предложил вынести в enum.
И еще на всякий случай рекомендую свериться со style guide по поводу нейминга, там вроде был CamelCase но это не точно.

2024-09-22 16:47 UTC, atpradical commented on src/components/toast/Toast.tsx
> +import React, { CSSProperties } from 'react'
React не стоит импортировать целиком.

2024-09-22 16:47 UTC, atpradical commented on src/components/toast/Toast.tsx
> +        </button>
я бы заменил на наш Button variant icon.
пропс type={'button'не вижу смысла добавлять, возможно не прав.

2024-09-22 17:06 UTC, blindstttealer commented on src/components/toast/Toast.tsx
> +  const typesClass = {
use memo обернуть

2024-09-23 06:16 UTC, Kristina-Tur approved these changes
В целом все отлично, хорошо проделанная работа. Единственное порекомендовала бы в файле .stories сделать одну функцию по созданию каждой истории.
const createStory = (
  message: string,
  variant?: 'error' | 'info' | 'success' | 'warning',
  duration?: number,
  progress?: boolean,
  icon?: React.ReactNode
): Story => ({
  render: () => {
    const onClickHandler = () => {
      showToast({
        message,
        variant,
        duration,
        progress,
        icon,
      })
    }

    return (
      <div style={style}>
        <div onClick={onClickHandler}>Показать тост</div>
        <Toaster />
      </div>
    )
  },
})

И дальше на каждой истории просто вызывать эту функцию и передавать нужные аргументы, что упростить читаемость кода и избежим дублирование

2024-09-23 14:13 UTC, merged