UI-26: Component SideBar
promising-inctagram/inctagram pull request #32
Opened 2024-09-22 23:14 UTC by atpradical

‼️ Зависимость от [[ui-21-dialog](https://github.com/promising-inctagram/inctagram/pull/29)](https://github.com/promising-inctagram/inctagram/pull/28)

Добавлен компонент SideBar.
![image](https://github.com/user-attachments/assets/4b147c40-8a72-4550-86f7-5ec4f2958e53)

2024-09-23 07:59 UTC, Kristina-Tur requested changes
Отличная работа. Есть пару комментариев. Еще стоит подумать над реализацией в сторибуке применение стилей c :active и :disabled

2024-09-23 07:59 UTC, Kristina-Tur commented on src/components/sidebar/menu-items.ts
> +}
только в home стоит слэш, стоит добавить ко всем путям

2024-09-23 07:59 UTC, Kristina-Tur commented on src/components/sidebar/SideBar.module.scss
> +  }
:not не поддерживает группировку селекторов.
 .group:not(:first-child):not(:last-child)

2024-09-23 08:14 UTC, atpradical commented on src/components/sidebar/menu-items.ts
> +}
исправил.

2024-09-23 08:18 UTC, atpradical commented on src/components/sidebar/SideBar.module.scss
> +  }
Не понял что именно здесь не поддерживается или не работает?
И как должно быть?

2024-09-23 08:23 UTC, atpradical commented
@Kristina-Tur 
> Еще стоит подумать над реализацией в сторибуке применение стилей c :active и :disabled

Думмаю, что эти дополнительные истории лишние: чтобы передать дата-атрибуты будет нужно написать второй компонент без использования map, плюс возможно потребуются обертки для работы с нектовым роутером.  При этом это не примитив, который в итоге попадет в UI-KIT, а частный lauout компонент который останется жить только в этом проекте. Пока что выглядит как код ради кода.

2024-09-23 08:56 UTC, Kristina-Tur commented on src/components/sidebar/SideBar.module.scss
> +  }
.group:not(:first-child):not(:last-child) вот как должно быть
отступы применяются корректно, но рекомендую, чтоб в будущем это случайно не вылезло, передавать :not один аргумент, т.к. некоторое количество не поддерживает

2024-09-23 09:09 UTC, Kristina-Tur approved these changes

2024-09-23 09:14 UTC, Kristina-Tur approved these changes

2024-09-23 09:14 UTC, atpradical commented on src/components/sidebar/SideBar.module.scss
> +  }
Да понял о чем ты. Но это добавили в 4 версии, и не работает только в одной opera для android. 
При чем там будет проигнорировано условие в селекторе и не будет марджина в меню - не страшно, рано или поздно добавят себе.

2024-09-24 04:33 UTC, tolkunio approved these changes

2024-09-24 08:49 UTC, merged