Controlled text field
promising-inctagram/inctagram pull request #33
Opened 2024-09-23 11:59 UTC by Kristina-Tur

Реализация контролируемого инпута

2024-09-23 22:12 UTC, Kulishevich approved these changes

2024-09-24 05:27 UTC, tolkunio requested changes

2024-09-24 05:27 UTC, tolkunio commented on src/components/controlled-text-field/ControlledTextField.tsx
> +  UseControllerProps<T>
я бы исключила возможность передавать rules и defaultValue для useControllerProps,
cчитаю что деволтное значение и схема валидации должно передаваться на уровне формы, а не компоненты.
можно через Omit убрать эти значения

2024-09-24 05:27 UTC, tolkunio commented on src/components/controlled-text-field/ControlledTextField.tsx
> +    defaultValue,
![image](https://github.com/user-attachments/assets/6994df3e-3ed3-4d29-87b1-cde5bad42ae4)
тут ошибку подсвечивает

2024-09-25 09:33 UTC, closed without merging