UI 14 component pagination
promising-inctagram/inctagram pull request #36
Opened 2024-09-23 22:43 UTC by Kulishevich

Добавлен компонент Pagination, в компоненте используется компонент Select. 
Сторонних библиотек установлено не было.
Есть небольшие моменты по поводу совместимости Select'а, которые как предполагаю нужно решать уже в Select.

2024-09-24 12:32 UTC, atpradical requested changes

2024-09-24 12:32 UTC, atpradical commented on src/components/pagination/Pagination.tsx
Компонент не реагирует на заданное кол-во элементов в селекте, т.е. селект есть но он никак не влияет на кол-во кнопок в пагинации.
Еще хорошо бы как то обрабатывать сценарий когда кол-во элементов умещается в 1 кнопку пагинации, т.е. тогда стрелочки и все остальное можно не показывать, но оставить при этом селект чтобы можно было поменять кол-во элементов на странице.

Очень рекомендую:
// https://www.freecodecamp.org/news/build-a-custom-pagination-component-in-react/

2024-09-24 12:32 UTC, atpradical commented on src/components/pagination/Pagination.tsx
> +  }
Саму функцию стоит вынести за пределы компоненты, например в кастомный хук, либо просто отдельно как утилиту. 
Это позволит улучшить читаемость, а еще она не будет генериться на каждый рендер.

2024-09-24 16:09 UTC, Kulishevich commented on src/components/select/Select.module.scss
> +  // width: 100%; //оч мешает
Проблема в том что класс передающийся Select'у присваивается триггеру и я не могу контролировать ширину container.

2024-09-24 16:15 UTC, Kulishevich commented on src/components/pagination/Pagination.tsx
> +        <span style={{ marginLeft: '24px', marginRight: '4px' }}>Show</span>
Согласен, сделал.

2024-09-28 06:17 UTC, atpradical approved these changes

2024-09-30 07:30 UTC, tolkunio approved these changes

2024-09-30 07:40 UTC, tolkunio commented on src/components/pagination/index.ts
> +import * from './Pagination'
![image](https://github.com/user-attachments/assets/0539a208-09c2-44a1-86d9-dc0d316179c4)
ошибка билда

2024-09-30 21:27 UTC, merged