In 57 log in query
promising-inctagram/inctagram pull request #57
Opened 2024-10-10 17:33 UTC by Kristina-Tur

Внесла изменения после ревью
1. Выпилила глобальный стэйт
2. Достаю текст ошибки из респонса и сохраняю в useState

2024-10-11 08:22 UTC, atpradical requested changes

2024-10-11 08:22 UTC, atpradical commented on src/locales/en/validation.ts
> +  unknownError: 'Unknown error',
loginError
unknownError

Cообщения которые присылает бекенд, сообщения на бекенде могут измениться в любой момент и фронт могут не предупредить. Поэтому их локализация должна быть именно на бекенде. 
validation.ts - это файл с переводами валидиции на фронте, не для сообщений с бека.

т.е. я предлагаю это выпилить здесь и там где ты это заюзала.

2024-10-11 08:22 UTC, atpradical commented on src/shared/api/auth/model/auth-slice.ts
> +export const { errorSelector, isAuthSelector } = slice.selectors
Пока нет никакой необходимости в использовании глобального стейта.
это нужно выпилить, мы работаем с RTK Query.

2024-10-11 08:22 UTC, atpradical commented on src/views/sign-in/model/useLoginValidation.tsx
> +    .regex(PASSWORD_REGEX, password.mustContain)
для email и password уже есть схемы валидации. есть смысл их переиспользовать и не дублировать код.

2024-10-11 08:22 UTC, atpradical commented on src/views/sign-in/ui/SignIn.module.scss
> +  height: auto;
Можно просто удалить heigh.

2024-10-11 08:22 UTC, atpradical commented on src/views/sign-in/ui/SignInForm.tsx
> +  onSubmit: (data: LoginArgs) => void
В onSubmit приходит data из формы, поэтому тип должен соответствовать данным полученным на форме.

2024-10-11 08:22 UTC, atpradical commented on src/views/sign-in/ui/SignInForm.tsx
> +    <form className={s.form} onSubmit={handleSubmit(onSubmit)}>
все callback выносим из разметки.

2024-10-11 08:22 UTC, atpradical commented on src/views/sign-in/ui/SignInForm.tsx
>    const { forgotPassword, labels, placeholders, submitButton } = t.signInPage.signInForm
с точки зрения архитектуры не лучший подход. 
useTranslation() - занимается переводами
useLoginValidation() - занимается данными для формы

когда они разделены - это лучше читается, чем когда все собирается в одну функцию.

2024-10-11 08:22 UTC, atpradical commented on src/views/sign-in/ui/SignInForm.tsx
> +        errorMessage={errors.email?.message}
когда уберешь null из TextFieldProps, то чтобы решить ошибку TS используй оператор нулевого слияния (??).

2024-10-11 08:22 UTC, atpradical commented on src/views/sign-in/ui/SignInPage.tsx
>    }
про Toolkit уже написал, он пока вообще не нужен для решения твоей задачи Выпили пожалуйста, и диспатчи и селекторы и слайс и тд.

2024-10-11 08:37 UTC, atpradical commented on src/views/sign-in/ui/SignInForm.tsx
Вопрос со звездочкой 😅

Почему в случае не правильных кредов, ты ошибку показываешь в поле с паролем?
![image](https://github.com/user-attachments/assets/bcc18850-8450-4cd8-809d-d957500faf07)

2024-10-11 12:06 UTC, Kristina-Tur commented on src/locales/en/validation.ts
> +  unknownError: 'Unknown error',
у меня по тз должно быть сообщение  The email or password are incorrect. Try
again please
бэкенд присылает Wrong credentials"
бэкенду надо изменить текст сообщения?

2024-10-11 12:41 UTC, Kristina-Tur commented on src/views/sign-in/ui/SignInForm.tsx
![image](https://github.com/user-attachments/assets/12e1dd14-d76f-4fb7-b4c0-de327d5f5fbf)
в фигме так показано

2024-10-11 14:24 UTC, atpradical commented on src/locales/en/validation.ts
> +  unknownError: 'Unknown error',
да

2024-10-11 14:25 UTC, atpradical commented on src/views/sign-in/ui/SignInForm.tsx
понятно

2024-10-11 14:25 UTC, atpradical commented on src/locales/en/validation.ts
> +  unknownError: 'Unknown error',
а что такое unknown error ?

2024-10-11 16:59 UTC, Kristina-Tur commented on src/locales/en/validation.ts
> +  unknownError: 'Unknown error',
unknown error, считай сама решила так сделать, ничего важного

2024-10-12 18:48 UTC, atpradical approved these changes

2024-10-12 18:48 UTC, atpradical commented on src/views/sign-in/ui/SignInForm.tsx
> +  const [errorMessage, setErrorMessage] = useState('')
из useForm можно вынуть setState и через него передать ошибку в поле формы.
Создавать отдельный стейт для хранения ошибки не нужно.

2024-10-12 18:48 UTC, atpradical commented on src/views/sign-in/ui/SignInForm.tsx
> +      const errorMessage = status === 401 ? data.errorsMessage : ''
тип unknown требует проверки. 
Сейчас ты просто глушишь TS когда уверяешь его что тип ошибки будет именно такой каким ты его ждешь (err as ErrorResponseLogin). Но в действительности ошибка здесь не обязательно будет ErrorResponseLogin. И тогда когда придет ошибка другая - приложение упадет.

2024-10-13 11:19 UTC, blindstttealer approved these changes

2024-10-15 08:17 UTC, merged